### ISSUE TITLE
Error train.py

### ISSUE THREAD

**Issue by felipeAvel** [pythonlessons/YOLOv3-object-detection-tutorial#1]
I want to thank you for your help.

I'm following the second step 

https://www.youtube.com/watch?v=b5_B9oNqaqE&list=PL7SlzVEU48Kh-NHJW9FWaLItZ5RvDoJ45&index=5

1 - clone git project https://github.com/pythonlessons/YOLOv3-object-detection-tutorial

2 - I paste the files **4_CLASS_test.txt** and **4_CLASS_test_classes.txt** generated in the first video
https://www.youtube.com/watch?v=XRVzuV9RexY&list=PL7SlzVEU48Kh-NHJW9FWaLItZ5RvDoJ45&index=3
I download **yolov3.weights** for **model_data**

3 - I execution the **convert.py**

4 -  I execution the **train.py**

5 - in the middle of execution the error

  2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[8,256,52,52] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node batch_normalization_72/FusedBatchNorm}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[loss_1/add_74/_5299]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[8,256,52,52] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node batch_normalization_72/FusedBatchNorm}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

https://drive.google.com/open?id=1agz8WKB7KJUvShGixa3JF2pOWW-OQT9u
https://drive.google.com/open?id=1m0MVJ8hP5nU5GBXtqVBttC49gnIkDdo3

**Comment by pythonlessons** [comment]
write error details

**Comment by felipeAvel** [comment]
I want to thank you for your help.

I'm following the second step

https://www.youtube.com/watch?v=b5_B9oNqaqE&list=PL7SlzVEU48Kh-NHJW9FWaLItZ5RvDoJ45&index=5

1 - clone git project https://github.com/pythonlessons/YOLOv3-object-detection-tutorial

2 - I paste the files 4_CLASS_test.txt and 4_CLASS_test_classes.txt generated in the first video https://www.youtube.com/watch?v=XRVzuV9RexY&list=PL7SlzVEU48Kh-NHJW9FWaLItZ5RvDoJ45&index=3 I download yolov3.weights for model_data

3 - I execution the convert.py

4 - I execution the train.py

5 - in the middle of execution the error

2 root error(s) found. (0) Resource exhausted: OOM when allocating tensor with shape[8,256,52,52] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [[{{node batch_normalization_72/FusedBatchNorm}}]] Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

 [[loss_1/add_74/_5299]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

(1) Resource exhausted: OOM when allocating tensor with shape[8,256,52,52] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [[{{node batch_normalization_72/FusedBatchNorm}}]] Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations. 0 derived errors ignored.

https://drive.google.com/open?id=1agz8WKB7KJUvShGixa3JF2pOWW-OQT9u https://drive.google.com/open?id=1m0MVJ8hP5nU5GBXtqVBttC49gnIkDdo3

**Comment by pythonlessons** [comment]
in line 76 "batch_size = 8" try to change this to 1 and check if you receive error, if not receiving try to increase this number

**Comment by felipeAvel** [comment]
Tks success execution 😎👍🏻
