### ISSUE TITLE
Keras taking 7+ hours to train one epoch on Google Colab.

### ISSUE THREAD

**Issue by fellowProgrammer** [pythonlessons/YOLOv3-object-detection-tutorial#10]
I followed the tutorial and labeled my dataset and converted it into the right format. I have around 14,000 images. When I tried to train on Google Colab it said the ETA for one epoch would be 7-9 HOURS. When I looked at the training time for one epoch in [this](https://pylessons.com/YOLOv3-custom-training/) tutorial (in the video at 11:04) it shows the ETA to be about 1 minute. Now that I look closely, I see that right before the training starts you see a "successfully opened CUDA library" message. I don't see that when training with Google Colab, could this be the problem?

Is there anything else I can do to make my training take a more reasonable amount of time. I changed the batch size to 8 but it didn't really make a difference on Google Colab.

I am running Keras 2.1.5 and Tensorflow 1.13.1. 

And yes I added a GPU to my runtime in Google Colab.

**Comment by pythonlessons** [comment]
Haven't tried to do this on Google Colab, in future I plan to do all this tutorial on tensorflow v2. then I will try to do same tutorial on google colab

**Comment by pythonlessons** [comment]
Started programming it with TF2.0. Will release quite soon
