### ISSUE TITLE
testing model file

### ISSUE THREAD

**Issue by Tourenathan-G5organisation** [pythonlessons/YOLOv3-object-detection-tutorial#11]
I have trained following the tutorial and i was stopped at the 83 epochs for early stopping.
I used the Kitti data for 2d color images.

I tried to test the resulting keras file produce after EarlyStopping and i have a problem with
`image_detect.py `which **_SyntaxError: 'break' outside loop_ at line `169**`

also with 
`realtime_detect.py` which shows nothing on the screen.

Please help

**Comment by pythonlessons** [comment]
fixed
