### ISSUE TITLE
input size

### ISSUE THREAD

**Issue by krishnak** [pythonlessons/YOLOv3-object-detection-tutorial#13]
https://github.com/pythonlessons/YOLOv3-object-detection-tutorial/blob/e08dee590f7b1d36a6caf9f9af2cff39476dc77e/YOLOv3-CSGO-detection/train.py#L109

I refer to the above line, what is the reason it is having NonexNonex3 instead of 416x416x3

**Comment by pythonlessons** [comment]
This is the way it creates model architecture, you can also do it with 416x416x3
