### ISSUE TITLE
Converting h5 model to tflite

### ISSUE THREAD

**Issue by manjeet87** [pythonlessons/YOLOv3-object-detection-tutorial#16]
Has anyone tried conversion of Keras-yolov3 model.h5 to tflite version? I have tried all approaches of converting keras h5 model to .tflite, but failed everytime with errors.

Can someone guide in respect to that

**Comment by pythonlessons** [comment]
Didn't tried, planning soon writing yolov3 in TF2.0, then will try. Subscribe for news
