### ISSUE TITLE
Runtime Error:get_session() is not available

### ISSUE THREAD

**Issue by sanjaykapilesh** [pythonlessons/YOLOv3-object-detection-tutorial#18]
Using TensorFlow backend.
Traceback (most recent call last):
  File "image_detect.py", line 164, in <module>
    yolo = YOLO()
  File "image_detect.py", line 39, in __init__
    self.sess = K.get_session()
  File "/home/beast/anaconda3/envs/yolo/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 379, in get_session
    '`get_session` is not available '
RuntimeError: `get_session` is not available when using TensorFlow 2.0.

**Comment by AbhinavKoul** [comment]
You need to specifically install Keras library either from anaconda installer or via pip to make it work

**Comment by pythonlessons** [comment]
Use TensorFlow 1.15

**Comment by AbhinavKoul** [comment]
i made it work in tensorflow 2

**Comment by Meghal17** [comment]
Abhinavkoul, how did you do that?

**Comment by pythonlessons** [comment]
> Abhinavkoul, how did you do that?

If you want it on TF2, move to this: https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3
Will be working on this for a while
