### ISSUE TITLE
TypeError: UMat() missing required argument 'ranges' (pos 2)

### ISSUE THREAD

**Issue by sagarsanjaysutar** [pythonlessons/YOLOv3-object-detection-tutorial#19]
original_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

I can't figure this out. It's constantly giving same error
TypeError: UMat() missing required argument 'ranges' (pos 2)

i tried: - 
1. original_image = cv2.cvtColor(cv2.UMat(image), cv2.COLOR_BGR2RGB)
2. original_image = cv2.cvtColor(np.float32(image), cv2.COLOR_BGR2RGB)
3. original_image = cv2.cvtColor((image).np(), cv2.COLOR_BGR2RGB)
4. original_image = cv2.cvtColor(np.array(image), cv2.COLOR_BGR2RGB)

**Comment by pythonlessons** [comment]
Can't reproduce you error
