### ISSUE TITLE
Error executing train.py or train_bottleneck.py - module 'keras.backend' has no attribute 'control_flow_ops'

### ISSUE THREAD

**Issue by CosmaBelli** [pythonlessons/YOLOv3-object-detection-tutorial#2]
Hello,
I experience the following error executing train.py or train_bottleneck.py on Colab.
I suppose the problem is related to filesystem path.

Do you have an idea?

Error output:
...
/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py:1281: UserWarning: Skipping loading of weights for layer conv2d_75 due to mismatch in shape ((30,) vs (255,)).
  weight_values[i].shape))
Load weights model_data/yolo_weights.h5.
Freeze the first 249 layers of total 252 layers.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3351: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    _main()
  File "train.py", line 35, in _main
    model = create_model(input_shape, anchors, num_classes, freeze_body=2, weights_path='model_data/yolo_weights.h5') # make sure you know what you freeze
  File "train.py", line 131, in create_model
    [*model_body.output, *y_true])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 451, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/core.py", line 716, in call
    return self.function(inputs, **arguments)
  File "/content/yolo3/model.py", line 394, in yolo_loss
    _, ignore_mask = K.control_flow_ops.while_loop(lambda b,*args: b<m, loop_body, [0, ignore_mask])
AttributeError: module 'keras.backend' has no attribute 'control_flow_ops'

Thank you

**Comment by CosmaBelli** [comment]
Additional information:
On Colab, I'm using
tf version 1.14.0
Keras 2.2.4-tf

Thank you

**Comment by pythonlessons** [comment]
Haven't faced this kind of error, not sure how to fix this

**Comment by vissieGP** [comment]
I had the same issue. I had to downgrade my keras:
sudo pip3.7 install keras==2.2.4

**Comment by pythonlessons** [comment]
> I had the same issue. I had to downgrade my keras:
> sudo pip3.7 install keras==2.2.4

Thanks
