### ISSUE TITLE
Creating custom class list.

### ISSUE THREAD

**Issue by TheNameKevinWasTaken** [pythonlessons/YOLOv3-object-detection-tutorial#20]
Making this as short as I can, following tutorial from https://pylessons.com/YOLOv3-WebCam/

How would I be able to set a custom list of classes using yolov3.weights?

In my case I only want to detect: ["backpack", "tie", "frisbee", "bottle", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple", "pottedplant", "remote", "keyboard", "cell phone", "clock", "scissors", "toothbrush"]

I've tried lots of solutions I've found online with no luck so I'm asking here. Thanks.

If its needed, info I'm using webcam_detect.py

**Comment by pythonlessons** [comment]
It's not an issue, it's laziness or you don't have programming skills and you want everything on a plate. It's simple, for example

> if predicted_class == 1: # person
>       do something with 1 class
> else:
>       do something with all other classes
>

**Comment by TheNameKevinWasTaken** [comment]
How I am handling it now is just checking `if predicted_class in object_list:` (object_list is just my list i had above) after `for i, c in reversed(list(enumerate(out_classes))):` so I am only returning the objects I want. However all 80 classes are still being detected just not displayed.

So I was wondering if you knew how to remove classes to see if it would speed up the detection. After trying everything I could find on the topic online I had no luck. I dont have Facebook or Twitter to reach out to you there, so I asked here, sorry if this is not the appropriate place.
