### ISSUE TITLE
cant run image_detect.py in colab

### ISSUE THREAD

**Issue by MasDrago** [pythonlessons/YOLOv3-object-detection-tutorial#25]
facing error: cannot connect to X server, when trying to run !python image_detect.py in colab for testing model on image.

**Comment by pythonlessons** [comment]
This is not an issue, I am not using !python image_detect.py in colab, maybe this is the reason? 
You write your own line and then tell me that this is an issue?
Use cells from the following cell to check if image detection works:
**Test by loading trained model:**

**Comment by MasDrago** [comment]
Thanks for your reply. But this is how you are supposed to run .py file in colab. If not this way, how can i run image_detect.py file in colab.

**Comment by pythonlessons** [comment]
Why do you need to do that?
Simply write the same code what is in image_detect.py script to the cell, and then run that cell

**Comment by MasDrago** [comment]
thanks
