### ISSUE TITLE
Not running on GPU

### ISSUE THREAD

**Issue by naitfox** [pythonlessons/YOLOv3-object-detection-tutorial#27]
I have a GTX 1660 Ti but the code is not running on the GPU

I have Tensorflow 1.15 and Tensorflow-gpu 1.15
keras 2.2.4

I changed the code here as well:
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

Any ideas? Please help

[image_detect.txt](https://github.com/pythonlessons/YOLOv3-object-detection-tutorial/files/5168509/image_detect.txt)

**Comment by pythonlessons** [comment]
check if you installed drivers, Cuda and cudnn correctly.
