### ISSUE TITLE
Where can we find this dataset?

### ISSUE THREAD

**Issue by krxat** [pythonlessons/YOLOv3-object-detection-tutorial#5]
Is there a way where I can get this dataset? If this is a custom made dataset, can you please share it?

**Comment by pythonlessons** [comment]
All information is given, if you want to use custom data, there is instructions how to [download](https://pylessons.com/YOLOv3-custom-data/) it. If you doing CS:GO, link to custom dataset you can find in this [post](https://pylessons.com/YOLOv3-CSGO-detection/)
