### ISSUE TITLE
 Dimension 0 in both shapes must be equal, but are 1 and 18

### ISSUE THREAD

**Issue by ancymicheal** [pythonlessons/YOLOv3-object-detection-tutorial#6]
my class file contains one class = uavperson.   After training, trained_weights_final.h5 is generated with file size 246.9 MB ...
while running image_detection, i got this error :
Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,906] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,906], [18,1024,1,1].

HOW TO SOLVE THIS....

**Comment by mananhfz** [comment]
Hi, I'm also receiving the same error. If you have found its solution please also share with me.
